name: everywhereGK
favicon: null
layout_spectrum: 0.12985760276205838
typography_spectrum: 0.03227346786297858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7486652780789882
  lightness: 0.2224923549219966
  saturation: 0.739337764447555
  rhythmicContrast: 0.9141655780840665
purpose: []
